### ISSUE TITLE
Add 'flake8' linting

### ISSUE THREAD

**Issue by johnsturgeon** [johnsturgeon/plex-tools#31]

**Comment by johnsturgeon** [comment]
```yaml
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

```
